// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

// Category Admin
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_CATEGORY = "SET_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// Product Admin
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_BY_ARRIVAL = "SET_PRODUCTS_BY_ARRIVAL";
export const SET_PRODUCTS_BY_SELL = "SET_PRODUCTS_BY_SELL";
export const SET_PRODUCTS_BY_CATEGORIES = "SET_PRODUCTS_BY_CATEGORIES";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SET_PRODUCT = "SET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_PRODUCTS_PRICE_RANGES = "SET_PRODUCTS_PRICE_RANGES";
export const SET_PRODUCTS_BY_SEARCH = "SET_PRODUCTS_BY_SEARCH"
export const SET_RELATED_PRODUCTS = "SET_RELATED_PRODUCTS"


// Cart
export const SET_CART = "SET_CART";